//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3082
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsE01E0934013C1012EA074479E8E58898))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// El tipo contiene vistas para EntitySets y AssociationSets que se generaron en tiempo de diseño.
    /// </Summary>
    public sealed class ViewsForBaseEntitySetsE01E0934013C1012EA074479E8E58898 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// El constructor almacena las vistas para las extensiones y también los valores hash generados basados en los metadatos y en las vistas y cierres de asignaciones
        /// </Summary>
        public ViewsForBaseEntitySetsE01E0934013C1012EA074479E8E58898()
        {
            this.EdmEntityContainerName = "NorthwindEFModelContext";
            this.StoreEntityContainerName = "NorthwindEFModelStoreContainer";
            this.HashOverMappingClosure = "b2812dbfaf67223ad7361cacf6fdb507";
            this.HashOverAllExtentViews = "58991e9a528a21a85ccffe49452ae51f";
            this.ViewCount = 37;
        }
        
        // El método devuelve la vista para un índice dado.
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                // vista devuelta para NorthwindEFModelStoreContainer.Categories
                return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.Categories", @"
    SELECT VALUE -- Constructing Categories
        [NorthwindEFModel.Store].Categories(T1.Categories_CategoryID, T1.Categories_CategoryName, T1.Categories_Description, T1.Categories_Picture)
    FROM (
        SELECT 
            T.CategoryID AS Categories_CategoryID, 
            T.CategoryName AS Categories_CategoryName, 
            T.Description AS Categories_Description, 
            T.Picture AS Categories_Picture, 
            True AS _from0
        FROM NorthwindEFModelContext.Categories AS T
    ) AS T1");
            }
            else
            {
                if ((index == 1))
                {
                    // vista devuelta para NorthwindEFModelStoreContainer.Customers
                    return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.Customers", @"
    SELECT VALUE -- Constructing Customers
        [NorthwindEFModel.Store].Customers(T1.Customers_CustomerID, T1.Customers_CompanyName, T1.Customers_ContactName, T1.Customers_ContactTitle, T1.Customers_Address, T1.Customers_City, T1.Customers_Region, T1.Customers_PostalCode, T1.Customers_Country, T1.Customers_Phone, T1.Customers_Fax)
    FROM (
        SELECT 
            T.CustomerID AS Customers_CustomerID, 
            T.CompanyName AS Customers_CompanyName, 
            T.ContactName AS Customers_ContactName, 
            T.ContactTitle AS Customers_ContactTitle, 
            T.Address AS Customers_Address, 
            T.City AS Customers_City, 
            T.Region AS Customers_Region, 
            T.PostalCode AS Customers_PostalCode, 
            T.Country AS Customers_Country, 
            T.Phone AS Customers_Phone, 
            T.Fax AS Customers_Fax, 
            True AS _from0
        FROM NorthwindEFModelContext.Customers AS T
    ) AS T1");
                }
                else
                {
                    if ((index == 2))
                    {
                        // vista devuelta para NorthwindEFModelStoreContainer.InternationalOrders
                        return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.InternationalOrders", @"
    SELECT VALUE -- Constructing InternationalOrders
        [NorthwindEFModel.Store].InternationalOrders(T1.InternationalOrders_OrderID, T1.InternationalOrders_CustomsDescription, T1.InternationalOrders_ExciseTax)
    FROM (
        SELECT 
            T.OrderID AS InternationalOrders_OrderID, 
            T.CustomsDescription AS InternationalOrders_CustomsDescription, 
            T.ExciseTax AS InternationalOrders_ExciseTax, 
            True AS _from0
        FROM NorthwindEFModelContext.InternationalOrders AS T
    ) AS T1");
                    }
                    else
                    {
                        if ((index == 3))
                        {
                            // vista devuelta para NorthwindEFModelStoreContainer.OrderDetails
                            return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.OrderDetails", @"
    SELECT VALUE -- Constructing OrderDetails
        [NorthwindEFModel.Store].OrderDetails(T1.OrderDetails_OrderID, T1.OrderDetails_ProductID, T1.OrderDetails_UnitPrice, T1.OrderDetails_Quantity, T1.OrderDetails_Discount)
    FROM (
        SELECT 
            T.OrderID AS OrderDetails_OrderID, 
            T.ProductID AS OrderDetails_ProductID, 
            T.UnitPrice AS OrderDetails_UnitPrice, 
            T.Quantity AS OrderDetails_Quantity, 
            T.Discount AS OrderDetails_Discount, 
            True AS _from0
        FROM NorthwindEFModelContext.OrderDetails AS T
    ) AS T1");
                        }
                        else
                        {
                            if ((index == 4))
                            {
                                // vista devuelta para NorthwindEFModelStoreContainer.Orders
                                return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.Orders", "\r\n    SELECT VALUE -- Constructing Orders\r\n        [NorthwindEFModel.Store].Order" +
                                        "s(T4.Orders_OrderID, T4.Orders_CustomerID, T4.Orders_EmployeeID, T4.Orders_Shipp" +
                                        "edDate, T4.Orders_ShipVia, T4.Orders_Freight, T4.Orders_ShipName, T4.Orders_Ship" +
                                        "Address, T4.Orders_ShipCity, T4.Orders_ShipRegion, T4.Orders_ShipPostalCode, T4." +
                                        "Orders_ShipCountry)\r\n    FROM (\r\n        SELECT T1.Orders_OrderID, T2.Orders_Cus" +
                                        "tomerID, T1.Orders_EmployeeID, T1.Orders_ShippedDate, T3.Orders_ShipVia, T1.Orde" +
                                        "rs_Freight, T1.Orders_ShipName, T1.Orders_ShipAddress, T1.Orders_ShipCity, T1.Or" +
                                        "ders_ShipRegion, T1.Orders_ShipPostalCode, T1.Orders_ShipCountry, T1._from0, (T2" +
                                        "._from1 AND T2._from1 IS NOT NULL) AS _from1, (T3._from2 AND T3._from2 IS NOT NU" +
                                        "LL) AS _from2\r\n        FROM  (\r\n            SELECT \r\n                T.OrderID A" +
                                        "S Orders_OrderID, \r\n                T.EmployeeID AS Orders_EmployeeID, \r\n       " +
                                        "         T.ShippedDate AS Orders_ShippedDate, \r\n                T.Freight AS Ord" +
                                        "ers_Freight, \r\n                T.ShipName AS Orders_ShipName, \r\n                " +
                                        "T.ShipAddress AS Orders_ShipAddress, \r\n                T.ShipCity AS Orders_Ship" +
                                        "City, \r\n                T.ShipRegion AS Orders_ShipRegion, \r\n                T.S" +
                                        "hipPostalCode AS Orders_ShipPostalCode, \r\n                T.ShipCountry AS Order" +
                                        "s_ShipCountry, \r\n                True AS _from0\r\n            FROM NorthwindEFMod" +
                                        "elContext.Orders AS T) AS T1\r\n            LEFT OUTER JOIN (\r\n            SELECT " +
                                        "\r\n                Key(T.Orders).OrderID AS Orders_OrderID, \r\n                Key" +
                                        "(T.Customers).CustomerID AS Orders_CustomerID, \r\n                True AS _from1\r" +
                                        "\n            FROM NorthwindEFModelContext.SYS_C009207 AS T) AS T2\r\n            O" +
                                        "N T1.Orders_OrderID = T2.Orders_OrderID\r\n            LEFT OUTER JOIN (\r\n        " +
                                        "    SELECT \r\n                Key(T.Orders).OrderID AS Orders_OrderID, \r\n        " +
                                        "        Key(T.Shippers).ShipperID AS Orders_ShipVia, \r\n                True AS _" +
                                        "from2\r\n            FROM NorthwindEFModelContext.SYS_C009206 AS T) AS T3\r\n       " +
                                        "     ON T1.Orders_OrderID = T3.Orders_OrderID\r\n    ) AS T4");
                            }
                            else
                            {
                                if ((index == 5))
                                {
                                    // vista devuelta para NorthwindEFModelStoreContainer.Products
                                    return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.Products", "\r\n    SELECT VALUE -- Constructing Products\r\n        [NorthwindEFModel.Store].Pro" +
                                            "ducts(T4.Products_ProductID, T4.Products_ProductName, T4.Products_SupplierID, T4" +
                                            ".Products_CategoryID, T4.Products_QuantityPerUnit, T4.Products_UnitPrice, T4.Pro" +
                                            "ducts_UnitsInStock, T4.Products_UnitsOnOrder, T4.Products_ReorderLevel, T4.Produ" +
                                            "cts_Discontinued, T4.Products_DiscontinuedDate)\r\n    FROM (\r\n        SELECT T1.P" +
                                            "roducts_ProductID, T1.Products_ProductName, T3.Products_SupplierID, T2.Products_" +
                                            "CategoryID, T1.Products_QuantityPerUnit, T1.Products_UnitPrice, T1.Products_Unit" +
                                            "sInStock, T1.Products_UnitsOnOrder, T1.Products_ReorderLevel, T1.Products_Discon" +
                                            "tinued, T1.Products_DiscontinuedDate, T1._from0, (T2._from1 AND T2._from1 IS NOT" +
                                            " NULL) AS _from1, (T3._from2 AND T3._from2 IS NOT NULL) AS _from2\r\n        FROM " +
                                            " (\r\n            SELECT \r\n                T.ProductID AS Products_ProductID, \r\n  " +
                                            "              T.ProductName AS Products_ProductName, \r\n                T.Quantit" +
                                            "yPerUnit AS Products_QuantityPerUnit, \r\n                T.UnitPrice AS Products_" +
                                            "UnitPrice, \r\n                T.UnitsInStock AS Products_UnitsInStock, \r\n        " +
                                            "        T.UnitsOnOrder AS Products_UnitsOnOrder, \r\n                T.ReorderLeve" +
                                            "l AS Products_ReorderLevel, \r\n                T.Discontinued AS Products_Discont" +
                                            "inued, \r\n                T.DiscontinuedDate AS Products_DiscontinuedDate, \r\n    " +
                                            "            True AS _from0\r\n            FROM NorthwindEFModelContext.Products AS" +
                                            " T) AS T1\r\n            LEFT OUTER JOIN (\r\n            SELECT \r\n                K" +
                                            "ey(T.Products).ProductID AS Products_ProductID, \r\n                Key(T.Categori" +
                                            "es).CategoryID AS Products_CategoryID, \r\n                True AS _from1\r\n       " +
                                            "     FROM NorthwindEFModelContext.SYS_C009217 AS T) AS T2\r\n            ON T1.Pro" +
                                            "ducts_ProductID = T2.Products_ProductID\r\n            LEFT OUTER JOIN (\r\n        " +
                                            "    SELECT \r\n                Key(T.Products).ProductID AS Products_ProductID, \r\n" +
                                            "                Key(T.Suppliers).SupplierID AS Products_SupplierID, \r\n          " +
                                            "      True AS _from2\r\n            FROM NorthwindEFModelContext.SYS_C009218 AS T)" +
                                            " AS T3\r\n            ON T1.Products_ProductID = T3.Products_ProductID\r\n    ) AS T" +
                                            "4");
                                }
                                else
                                {
                                    if ((index == 6))
                                    {
                                        // vista devuelta para NorthwindEFModelStoreContainer.Shippers
                                        return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.Shippers", @"
    SELECT VALUE -- Constructing Shippers
        [NorthwindEFModel.Store].Shippers(T1.Shippers_ShipperID, T1.Shippers_CompanyName, T1.Shippers_Phone)
    FROM (
        SELECT 
            T.ShipperID AS Shippers_ShipperID, 
            T.CompanyName AS Shippers_CompanyName, 
            T.Phone AS Shippers_Phone, 
            True AS _from0
        FROM NorthwindEFModelContext.Shippers AS T
    ) AS T1");
                                    }
                                    else
                                    {
                                        if ((index == 7))
                                        {
                                            // vista devuelta para NorthwindEFModelStoreContainer.Suppliers
                                            return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.Suppliers", @"
    SELECT VALUE -- Constructing Suppliers
        [NorthwindEFModel.Store].Suppliers(T1.Suppliers_SupplierID, T1.Suppliers_CompanyName, T1.Suppliers_ContactName, T1.Suppliers_ContactTitle, T1.Suppliers_Address, T1.Suppliers_City, T1.Suppliers_Region, T1.Suppliers_PostalCode, T1.Suppliers_Country, T1.Suppliers_Phone, T1.Suppliers_Fax, T1.Suppliers_HomePage)
    FROM (
        SELECT 
            T.SupplierID AS Suppliers_SupplierID, 
            T.CompanyName AS Suppliers_CompanyName, 
            T.ContactName AS Suppliers_ContactName, 
            T.ContactTitle AS Suppliers_ContactTitle, 
            T.Address AS Suppliers_Address, 
            T.City AS Suppliers_City, 
            T.Region AS Suppliers_Region, 
            T.PostalCode AS Suppliers_PostalCode, 
            T.Country AS Suppliers_Country, 
            T.Phone AS Suppliers_Phone, 
            T.Fax AS Suppliers_Fax, 
            T.HomePage AS Suppliers_HomePage, 
            True AS _from0
        FROM NorthwindEFModelContext.Suppliers AS T
    ) AS T1");
                                        }
                                        else
                                        {
                                            if ((index == 8))
                                            {
                                                // vista devuelta para NorthwindEFModelContext.Categories
                                                return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.Categories", @"
    SELECT VALUE -- Constructing Categories
        NorthwindEFModel.Categories(T1.Categories_CategoryID, T1.Categories_CategoryName, T1.Categories_Description, T1.Categories_Picture)
    FROM (
        SELECT 
            T.CategoryID AS Categories_CategoryID, 
            T.CategoryName AS Categories_CategoryName, 
            T.Description AS Categories_Description, 
            T.Picture AS Categories_Picture, 
            True AS _from0
        FROM NorthwindEFModelStoreContainer.Categories AS T
    ) AS T1");
                                            }
                                            else
                                            {
                                                if ((index == 9))
                                                {
                                                    // vista devuelta para NorthwindEFModelContext.Customers
                                                    return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.Customers", @"
    SELECT VALUE -- Constructing Customers
        NorthwindEFModel.Customers(T1.Customers_CustomerID, T1.Customers_CompanyName, T1.Customers_ContactName, T1.Customers_ContactTitle, T1.Customers_Address, T1.Customers_City, T1.Customers_Region, T1.Customers_PostalCode, T1.Customers_Country, T1.Customers_Phone, T1.Customers_Fax)
    FROM (
        SELECT 
            T.CustomerID AS Customers_CustomerID, 
            T.CompanyName AS Customers_CompanyName, 
            T.ContactName AS Customers_ContactName, 
            T.ContactTitle AS Customers_ContactTitle, 
            T.Address AS Customers_Address, 
            T.City AS Customers_City, 
            T.Region AS Customers_Region, 
            T.PostalCode AS Customers_PostalCode, 
            T.Country AS Customers_Country, 
            T.Phone AS Customers_Phone, 
            T.Fax AS Customers_Fax, 
            True AS _from0
        FROM NorthwindEFModelStoreContainer.Customers AS T
    ) AS T1");
                                                }
                                                else
                                                {
                                                    if ((index == 10))
                                                    {
                                                        // vista devuelta para NorthwindEFModelContext.InternationalOrders
                                                        return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.InternationalOrders", @"
    SELECT VALUE -- Constructing InternationalOrders
        NorthwindEFModel.InternationalOrders(T1.InternationalOrders_OrderID, T1.InternationalOrders_CustomsDescription, T1.InternationalOrders_ExciseTax)
    FROM (
        SELECT 
            T.OrderID AS InternationalOrders_OrderID, 
            T.CustomsDescription AS InternationalOrders_CustomsDescription, 
            T.ExciseTax AS InternationalOrders_ExciseTax, 
            True AS _from0, 
            T.OrderID AS [SYS_C009244.InternationalOrders.OrderID]
        FROM NorthwindEFModelStoreContainer.InternationalOrders AS T
    ) AS T1");
                                                    }
                                                    else
                                                    {
                                                        if ((index == 11))
                                                        {
                                                            // vista devuelta para NorthwindEFModelContext.OrderDetails
                                                            return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.OrderDetails", @"
    SELECT VALUE -- Constructing OrderDetails
        NorthwindEFModel.OrderDetails(T1.OrderDetails_OrderID, T1.OrderDetails_ProductID, T1.OrderDetails_UnitPrice, T1.OrderDetails_Quantity, T1.OrderDetails_Discount) WITH 
        RELATIONSHIP(CREATEREF(NorthwindEFModelContext.Orders, ROW(T1.[SYS_C009233.Orders.OrderID]),NorthwindEFModel.Orders),NorthwindEFModel.SYS_C009233,OrderDetails,Orders) 
        RELATIONSHIP(CREATEREF(NorthwindEFModelContext.Products, ROW(T1.[SYS_C009234.Products.ProductID]),NorthwindEFModel.Products),NorthwindEFModel.SYS_C009234,OrderDetails,Products) 
    FROM (
        SELECT 
            T.OrderID AS OrderDetails_OrderID, 
            T.ProductID AS OrderDetails_ProductID, 
            T.UnitPrice AS OrderDetails_UnitPrice, 
            T.Quantity AS OrderDetails_Quantity, 
            T.Discount AS OrderDetails_Discount, 
            True AS _from0, 
            T.OrderID AS [SYS_C009233.Orders.OrderID], 
            T.ProductID AS [SYS_C009234.Products.ProductID]
        FROM NorthwindEFModelStoreContainer.OrderDetails AS T
    ) AS T1");
                                                        }
                                                        else
                                                        {
                                                            if ((index == 12))
                                                            {
                                                                // vista devuelta para NorthwindEFModelContext.Orders
                                                                return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.Orders", @"
    SELECT VALUE -- Constructing Orders
        NorthwindEFModel.Orders(T1.Orders_OrderID, T1.Orders_EmployeeID, T1.Orders_ShippedDate, T1.Orders_Freight, T1.Orders_ShipName, T1.Orders_ShipAddress, T1.Orders_ShipCity, T1.Orders_ShipRegion, T1.Orders_ShipPostalCode, T1.Orders_ShipCountry) WITH 
        RELATIONSHIP(CREATEREF(NorthwindEFModelContext.Customers, ROW(T1.[SYS_C009207.Customers.CustomerID]),NorthwindEFModel.Customers),NorthwindEFModel.SYS_C009207,Orders,Customers) 
        RELATIONSHIP(CREATEREF(NorthwindEFModelContext.Shippers, ROW(T1.[SYS_C009206.Shippers.ShipperID]),NorthwindEFModel.Shippers),NorthwindEFModel.SYS_C009206,Orders,Shippers) 
    FROM (
        SELECT 
            T.OrderID AS Orders_OrderID, 
            T.EmployeeID AS Orders_EmployeeID, 
            T.ShippedDate AS Orders_ShippedDate, 
            T.Freight AS Orders_Freight, 
            T.ShipName AS Orders_ShipName, 
            T.ShipAddress AS Orders_ShipAddress, 
            T.ShipCity AS Orders_ShipCity, 
            T.ShipRegion AS Orders_ShipRegion, 
            T.ShipPostalCode AS Orders_ShipPostalCode, 
            T.ShipCountry AS Orders_ShipCountry, 
            True AS _from0, 
            T.CustomerID AS [SYS_C009207.Customers.CustomerID], 
            T.ShipVia AS [SYS_C009206.Shippers.ShipperID]
        FROM NorthwindEFModelStoreContainer.Orders AS T
    ) AS T1");
                                                            }
                                                            else
                                                            {
                                                                if ((index == 13))
                                                                {
                                                                    // vista devuelta para NorthwindEFModelContext.Products
                                                                    return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.Products", @"
    SELECT VALUE -- Constructing Products
        NorthwindEFModel.Products(T1.Products_ProductID, T1.Products_ProductName, T1.Products_QuantityPerUnit, T1.Products_UnitPrice, T1.Products_UnitsInStock, T1.Products_UnitsOnOrder, T1.Products_ReorderLevel, T1.Products_Discontinued, T1.Products_DiscontinuedDate) WITH 
        RELATIONSHIP(CREATEREF(NorthwindEFModelContext.Categories, ROW(T1.[SYS_C009217.Categories.CategoryID]),NorthwindEFModel.Categories),NorthwindEFModel.SYS_C009217,Products,Categories) 
        RELATIONSHIP(CREATEREF(NorthwindEFModelContext.Suppliers, ROW(T1.[SYS_C009218.Suppliers.SupplierID]),NorthwindEFModel.Suppliers),NorthwindEFModel.SYS_C009218,Products,Suppliers) 
    FROM (
        SELECT 
            T.ProductID AS Products_ProductID, 
            T.ProductName AS Products_ProductName, 
            T.QuantityPerUnit AS Products_QuantityPerUnit, 
            T.UnitPrice AS Products_UnitPrice, 
            T.UnitsInStock AS Products_UnitsInStock, 
            T.UnitsOnOrder AS Products_UnitsOnOrder, 
            T.ReorderLevel AS Products_ReorderLevel, 
            T.Discontinued AS Products_Discontinued, 
            T.DiscontinuedDate AS Products_DiscontinuedDate, 
            True AS _from0, 
            T.CategoryID AS [SYS_C009217.Categories.CategoryID], 
            T.SupplierID AS [SYS_C009218.Suppliers.SupplierID]
        FROM NorthwindEFModelStoreContainer.Products AS T
    ) AS T1");
                                                                }
                                                                else
                                                                {
                                                                    if ((index == 14))
                                                                    {
                                                                        // vista devuelta para NorthwindEFModelContext.Shippers
                                                                        return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.Shippers", @"
    SELECT VALUE -- Constructing Shippers
        NorthwindEFModel.Shippers(T1.Shippers_ShipperID, T1.Shippers_CompanyName, T1.Shippers_Phone)
    FROM (
        SELECT 
            T.ShipperID AS Shippers_ShipperID, 
            T.CompanyName AS Shippers_CompanyName, 
            T.Phone AS Shippers_Phone, 
            True AS _from0
        FROM NorthwindEFModelStoreContainer.Shippers AS T
    ) AS T1");
                                                                    }
                                                                    else
                                                                    {
                                                                        if ((index == 15))
                                                                        {
                                                                            // vista devuelta para NorthwindEFModelContext.Suppliers
                                                                            return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.Suppliers", @"
    SELECT VALUE -- Constructing Suppliers
        NorthwindEFModel.Suppliers(T1.Suppliers_SupplierID, T1.Suppliers_CompanyName, T1.Suppliers_ContactName, T1.Suppliers_ContactTitle, T1.Suppliers_Address, T1.Suppliers_City, T1.Suppliers_Region, T1.Suppliers_PostalCode, T1.Suppliers_Country, T1.Suppliers_Phone, T1.Suppliers_Fax, T1.Suppliers_HomePage)
    FROM (
        SELECT 
            T.SupplierID AS Suppliers_SupplierID, 
            T.CompanyName AS Suppliers_CompanyName, 
            T.ContactName AS Suppliers_ContactName, 
            T.ContactTitle AS Suppliers_ContactTitle, 
            T.Address AS Suppliers_Address, 
            T.City AS Suppliers_City, 
            T.Region AS Suppliers_Region, 
            T.PostalCode AS Suppliers_PostalCode, 
            T.Country AS Suppliers_Country, 
            T.Phone AS Suppliers_Phone, 
            T.Fax AS Suppliers_Fax, 
            T.HomePage AS Suppliers_HomePage, 
            True AS _from0
        FROM NorthwindEFModelStoreContainer.Suppliers AS T
    ) AS T1");
                                                                        }
                                                                        else
                                                                        {
                                                                            if ((index == 16))
                                                                            {
                                                                                // vista devuelta para NorthwindEFModelContext.SYS_C009217
                                                                                return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.SYS_C009217", @"
    SELECT VALUE -- Constructing SYS_C009217
        NorthwindEFModel.SYS_C009217(T3.[SYS_C009217.Categories], T3.[SYS_C009217.Products])
    FROM (
        SELECT -- Constructing Categories
            CreateRef(NorthwindEFModelContext.Categories, row(T2.[SYS_C009217.Categories.CategoryID]),NorthwindEFModel.Categories) AS [SYS_C009217.Categories], 
            T2.[SYS_C009217.Products]
        FROM (
            SELECT -- Constructing Products
                CreateRef(NorthwindEFModelContext.Products, row(T1.[SYS_C009217.Products.ProductID]),NorthwindEFModel.Products) AS [SYS_C009217.Products], 
                T1.[SYS_C009217.Categories.CategoryID]
            FROM (
                SELECT 
                    T.CategoryID AS [SYS_C009217.Categories.CategoryID], 
                    T.ProductID AS [SYS_C009217.Products.ProductID], 
                    True AS _from0
                FROM NorthwindEFModelStoreContainer.Products AS T
                WHERE T.CategoryID IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
                                                                            }
                                                                            else
                                                                            {
                                                                                if ((index == 17))
                                                                                {
                                                                                    // vista devuelta para NorthwindEFModelContext.SYS_C009207
                                                                                    return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.SYS_C009207", @"
    SELECT VALUE -- Constructing SYS_C009207
        NorthwindEFModel.SYS_C009207(T3.[SYS_C009207.Customers], T3.[SYS_C009207.Orders])
    FROM (
        SELECT -- Constructing Customers
            CreateRef(NorthwindEFModelContext.Customers, row(T2.[SYS_C009207.Customers.CustomerID]),NorthwindEFModel.Customers) AS [SYS_C009207.Customers], 
            T2.[SYS_C009207.Orders]
        FROM (
            SELECT -- Constructing Orders
                CreateRef(NorthwindEFModelContext.Orders, row(T1.[SYS_C009207.Orders.OrderID]),NorthwindEFModel.Orders) AS [SYS_C009207.Orders], 
                T1.[SYS_C009207.Customers.CustomerID]
            FROM (
                SELECT 
                    T.CustomerID AS [SYS_C009207.Customers.CustomerID], 
                    T.OrderID AS [SYS_C009207.Orders.OrderID], 
                    True AS _from0
                FROM NorthwindEFModelStoreContainer.Orders AS T
                WHERE T.CustomerID IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
                                                                                }
                                                                                else
                                                                                {
                                                                                    if ((index == 18))
                                                                                    {
                                                                                        // vista devuelta para NorthwindEFModelContext.SYS_C009244
                                                                                        return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.SYS_C009244", @"
    SELECT VALUE -- Constructing SYS_C009244
        NorthwindEFModel.SYS_C009244(T3.[SYS_C009244.Orders], T3.[SYS_C009244.InternationalOrders])
    FROM (
        SELECT -- Constructing Orders
            CreateRef(NorthwindEFModelContext.Orders, row(T2.[SYS_C009244.Orders.OrderID]),NorthwindEFModel.Orders) AS [SYS_C009244.Orders], 
            T2.[SYS_C009244.InternationalOrders]
        FROM (
            SELECT -- Constructing InternationalOrders
                CreateRef(NorthwindEFModelContext.InternationalOrders, row(T1.[SYS_C009244.InternationalOrders.OrderID]),NorthwindEFModel.InternationalOrders) AS [SYS_C009244.InternationalOrders], 
                T1.[SYS_C009244.Orders.OrderID]
            FROM (
                SELECT 
                    T.OrderID AS [SYS_C009244.Orders.OrderID], 
                    T.OrderID AS [SYS_C009244.InternationalOrders.OrderID], 
                    True AS _from0
                FROM NorthwindEFModelStoreContainer.InternationalOrders AS T
            ) AS T1
        ) AS T2
    ) AS T3");
                                                                                    }
                                                                                    else
                                                                                    {
                                                                                        if ((index == 19))
                                                                                        {
                                                                                            // vista devuelta para NorthwindEFModelContext.SYS_C009233
                                                                                            return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.SYS_C009233", @"
    SELECT VALUE -- Constructing SYS_C009233
        NorthwindEFModel.SYS_C009233(T3.[SYS_C009233.Orders], T3.[SYS_C009233.OrderDetails])
    FROM (
        SELECT -- Constructing Orders
            CreateRef(NorthwindEFModelContext.Orders, row(T2.[SYS_C009233.Orders.OrderID]),NorthwindEFModel.Orders) AS [SYS_C009233.Orders], 
            T2.[SYS_C009233.OrderDetails]
        FROM (
            SELECT -- Constructing OrderDetails
                CreateRef(NorthwindEFModelContext.OrderDetails, row(T1.[SYS_C009233.OrderDetails.OrderID], T1.[SYS_C009233.OrderDetails.ProductID]),NorthwindEFModel.OrderDetails) AS [SYS_C009233.OrderDetails], 
                T1.[SYS_C009233.Orders.OrderID]
            FROM (
                SELECT 
                    T.OrderID AS [SYS_C009233.Orders.OrderID], 
                    T.OrderID AS [SYS_C009233.OrderDetails.OrderID], 
                    T.ProductID AS [SYS_C009233.OrderDetails.ProductID], 
                    True AS _from0
                FROM NorthwindEFModelStoreContainer.OrderDetails AS T
            ) AS T1
        ) AS T2
    ) AS T3");
                                                                                        }
                                                                                        else
                                                                                        {
                                                                                            if ((index == 20))
                                                                                            {
                                                                                                // vista devuelta para NorthwindEFModelContext.SYS_C009234
                                                                                                return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.SYS_C009234", @"
    SELECT VALUE -- Constructing SYS_C009234
        NorthwindEFModel.SYS_C009234(T3.[SYS_C009234.Products], T3.[SYS_C009234.OrderDetails])
    FROM (
        SELECT -- Constructing Products
            CreateRef(NorthwindEFModelContext.Products, row(T2.[SYS_C009234.Products.ProductID]),NorthwindEFModel.Products) AS [SYS_C009234.Products], 
            T2.[SYS_C009234.OrderDetails]
        FROM (
            SELECT -- Constructing OrderDetails
                CreateRef(NorthwindEFModelContext.OrderDetails, row(T1.[SYS_C009234.OrderDetails.OrderID], T1.[SYS_C009234.OrderDetails.ProductID]),NorthwindEFModel.OrderDetails) AS [SYS_C009234.OrderDetails], 
                T1.[SYS_C009234.Products.ProductID]
            FROM (
                SELECT 
                    T.ProductID AS [SYS_C009234.Products.ProductID], 
                    T.OrderID AS [SYS_C009234.OrderDetails.OrderID], 
                    T.ProductID AS [SYS_C009234.OrderDetails.ProductID], 
                    True AS _from0
                FROM NorthwindEFModelStoreContainer.OrderDetails AS T
            ) AS T1
        ) AS T2
    ) AS T3");
                                                                                            }
                                                                                            else
                                                                                            {
                                                                                                if ((index == 21))
                                                                                                {
                                                                                                    // vista devuelta para NorthwindEFModelContext.SYS_C009206
                                                                                                    return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.SYS_C009206", @"
    SELECT VALUE -- Constructing SYS_C009206
        NorthwindEFModel.SYS_C009206(T3.[SYS_C009206.Shippers], T3.[SYS_C009206.Orders])
    FROM (
        SELECT -- Constructing Shippers
            CreateRef(NorthwindEFModelContext.Shippers, row(T2.[SYS_C009206.Shippers.ShipperID]),NorthwindEFModel.Shippers) AS [SYS_C009206.Shippers], 
            T2.[SYS_C009206.Orders]
        FROM (
            SELECT -- Constructing Orders
                CreateRef(NorthwindEFModelContext.Orders, row(T1.[SYS_C009206.Orders.OrderID]),NorthwindEFModel.Orders) AS [SYS_C009206.Orders], 
                T1.[SYS_C009206.Shippers.ShipperID]
            FROM (
                SELECT 
                    T.ShipVia AS [SYS_C009206.Shippers.ShipperID], 
                    T.OrderID AS [SYS_C009206.Orders.OrderID], 
                    True AS _from0
                FROM NorthwindEFModelStoreContainer.Orders AS T
                WHERE T.ShipVia IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
                                                                                                }
                                                                                                else
                                                                                                {
                                                                                                    if ((index == 22))
                                                                                                    {
                                                                                                        // vista devuelta para NorthwindEFModelContext.SYS_C009218
                                                                                                        return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.SYS_C009218", @"
    SELECT VALUE -- Constructing SYS_C009218
        NorthwindEFModel.SYS_C009218(T3.[SYS_C009218.Suppliers], T3.[SYS_C009218.Products])
    FROM (
        SELECT -- Constructing Suppliers
            CreateRef(NorthwindEFModelContext.Suppliers, row(T2.[SYS_C009218.Suppliers.SupplierID]),NorthwindEFModel.Suppliers) AS [SYS_C009218.Suppliers], 
            T2.[SYS_C009218.Products]
        FROM (
            SELECT -- Constructing Products
                CreateRef(NorthwindEFModelContext.Products, row(T1.[SYS_C009218.Products.ProductID]),NorthwindEFModel.Products) AS [SYS_C009218.Products], 
                T1.[SYS_C009218.Suppliers.SupplierID]
            FROM (
                SELECT 
                    T.SupplierID AS [SYS_C009218.Suppliers.SupplierID], 
                    T.ProductID AS [SYS_C009218.Products.ProductID], 
                    True AS _from0
                FROM NorthwindEFModelStoreContainer.Products AS T
                WHERE T.SupplierID IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
                                                                                                    }
                                                                                                    else
                                                                                                    {
                                                                                                        if ((index == 23))
                                                                                                        {
                                                                                                            // vista devuelta para NorthwindEFModelStoreContainer.Employees
                                                                                                            return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.Employees", "\r\n    SELECT VALUE -- Constructing Employees\r\n        [NorthwindEFModel.Store].Em" +
                                                                                                                    "ployees(T3.Employees_EmployeeID, T3.Employees_LastName, T3.Employees_FirstName, " +
                                                                                                                    "T3.Employees_Title, T3.Employees_TitleOfCourtesy, T3.Employees_BirthDate, T3.Emp" +
                                                                                                                    "loyees_HireDate, T3.Employees_Address, T3.Employees_City, T3.Employees_Region, T" +
                                                                                                                    "3.Employees_PostalCode, T3.Employees_Country, T3.Employees_HomePhone, T3.Employe" +
                                                                                                                    "es_Extension, T3.Employees_Photo, T3.Employees_Notes, T3.Employees_ReportsTo, T3" +
                                                                                                                    ".Employees_PhotoPath)\r\n    FROM (\r\n        SELECT T1.Employees_EmployeeID, T1.Em" +
                                                                                                                    "ployees_LastName, T1.Employees_FirstName, T1.Employees_Title, T1.Employees_Title" +
                                                                                                                    "OfCourtesy, T1.Employees_BirthDate, T1.Employees_HireDate, T1.Employees_Address," +
                                                                                                                    " T1.Employees_City, T1.Employees_Region, T1.Employees_PostalCode, T1.Employees_C" +
                                                                                                                    "ountry, T1.Employees_HomePhone, T1.Employees_Extension, T1.Employees_Photo, T1.E" +
                                                                                                                    "mployees_Notes, T2.Employees_ReportsTo, T1.Employees_PhotoPath, T1._from0, (T2._" +
                                                                                                                    "from1 AND T2._from1 IS NOT NULL) AS _from1\r\n        FROM  (\r\n            SELECT " +
                                                                                                                    "\r\n                T.EmployeeID AS Employees_EmployeeID, \r\n                T.Last" +
                                                                                                                    "Name AS Employees_LastName, \r\n                T.FirstName AS Employees_FirstName" +
                                                                                                                    ", \r\n                T.Title AS Employees_Title, \r\n                T.TitleOfCourt" +
                                                                                                                    "esy AS Employees_TitleOfCourtesy, \r\n                T.BirthDate AS Employees_Bir" +
                                                                                                                    "thDate, \r\n                T.HireDate AS Employees_HireDate, \r\n                T." +
                                                                                                                    "Address AS Employees_Address, \r\n                T.City AS Employees_City, \r\n    " +
                                                                                                                    "            T.Region AS Employees_Region, \r\n                T.PostalCode AS Empl" +
                                                                                                                    "oyees_PostalCode, \r\n                T.Country AS Employees_Country, \r\n          " +
                                                                                                                    "      T.HomePhone AS Employees_HomePhone, \r\n                T.Extension AS Emplo" +
                                                                                                                    "yees_Extension, \r\n                T.Photo AS Employees_Photo, \r\n                " +
                                                                                                                    "T.Notes AS Employees_Notes, \r\n                T.PhotoPath AS Employees_PhotoPath" +
                                                                                                                    ", \r\n                True AS _from0\r\n            FROM NorthwindEFModelContext.Emp" +
                                                                                                                    "loyees AS T) AS T1\r\n            LEFT OUTER JOIN (\r\n            SELECT \r\n        " +
                                                                                                                    "        Key(T.Employees1).EmployeeID AS Employees_EmployeeID, \r\n                " +
                                                                                                                    "Key(T.Employees).EmployeeID AS Employees_ReportsTo, \r\n                True AS _f" +
                                                                                                                    "rom1\r\n            FROM NorthwindEFModelContext.SYS_C009204 AS T) AS T2\r\n        " +
                                                                                                                    "    ON T1.Employees_EmployeeID = T2.Employees_EmployeeID\r\n    ) AS T3");
                                                                                                        }
                                                                                                        else
                                                                                                        {
                                                                                                            if ((index == 24))
                                                                                                            {
                                                                                                                // vista devuelta para NorthwindEFModelStoreContainer.Regions
                                                                                                                return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.Regions", @"
    SELECT VALUE -- Constructing Regions
        [NorthwindEFModel.Store].Regions(T1.Regions_RegionID, T1.Regions_RegionDescription)
    FROM (
        SELECT 
            T.RegionID AS Regions_RegionID, 
            T.RegionDescription AS Regions_RegionDescription, 
            True AS _from0
        FROM NorthwindEFModelContext.Regions AS T
    ) AS T1");
                                                                                                            }
                                                                                                            else
                                                                                                            {
                                                                                                                if ((index == 25))
                                                                                                                {
                                                                                                                    // vista devuelta para NorthwindEFModelStoreContainer.Territories
                                                                                                                    return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.Territories", @"
    SELECT VALUE -- Constructing Territories
        [NorthwindEFModel.Store].Territories(T3.Territories_TerritoryID, T3.Territories_TerritoryDescription, T3.Territories_RegionID)
    FROM (
        SELECT T1.Territories_TerritoryID, T2.Territories_TerritoryDescription, T1.Territories_RegionID, T2._from0, T1._from1
        FROM  (
            SELECT 
                Key(T.Territories).TerritoryID AS Territories_TerritoryID, 
                Key(T.Regions).RegionID AS Territories_RegionID, 
                True AS _from1
            FROM NorthwindEFModelContext.SYS_C009226 AS T) AS T1
            INNER JOIN (
            SELECT 
                T.TerritoryID AS Territories_TerritoryID, 
                T.TerritoryDescription AS Territories_TerritoryDescription, 
                True AS _from0
            FROM NorthwindEFModelContext.Territories AS T) AS T2
            ON T1.Territories_TerritoryID = T2.Territories_TerritoryID
    ) AS T3");
                                                                                                                }
                                                                                                                else
                                                                                                                {
                                                                                                                    if ((index == 26))
                                                                                                                    {
                                                                                                                        // vista devuelta para NorthwindEFModelStoreContainer.EmployeesTerritories
                                                                                                                        return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.EmployeesTerritories", @"
    SELECT VALUE -- Constructing EmployeesTerritories
        [NorthwindEFModel.Store].EmployeesTerritories(T1.EmployeesTerritories_EmployeeID, T1.EmployeesTerritories_TerritoryID)
    FROM (
        SELECT 
            Key(T.Employees).EmployeeID AS EmployeesTerritories_EmployeeID, 
            Key(T.Territories).TerritoryID AS EmployeesTerritories_TerritoryID, 
            True AS _from0
        FROM NorthwindEFModelContext.EmployeesTerritories AS T
    ) AS T1");
                                                                                                                    }
                                                                                                                    else
                                                                                                                    {
                                                                                                                        if ((index == 27))
                                                                                                                        {
                                                                                                                            // vista devuelta para NorthwindEFModelContext.Employees
                                                                                                                            return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.Employees", "\r\n    SELECT VALUE -- Constructing Employees\r\n        NorthwindEFModel.Employees(" +
                                                                                                                                    "T1.Employees_EmployeeID, T1.Employees_LastName, T1.Employees_FirstName, T1.Emplo" +
                                                                                                                                    "yees_Title, T1.Employees_TitleOfCourtesy, T1.Employees_BirthDate, T1.Employees_H" +
                                                                                                                                    "ireDate, T1.Employees_Address, T1.Employees_City, T1.Employees_Region, T1.Employ" +
                                                                                                                                    "ees_PostalCode, T1.Employees_Country, T1.Employees_HomePhone, T1.Employees_Exten" +
                                                                                                                                    "sion, T1.Employees_Photo, T1.Employees_Notes, T1.Employees_PhotoPath) WITH \r\n   " +
                                                                                                                                    "     RELATIONSHIP(CREATEREF(NorthwindEFModelContext.Employees, ROW(T1.[SYS_C0092" +
                                                                                                                                    "04.Employees.EmployeeID]),NorthwindEFModel.Employees),NorthwindEFModel.SYS_C0092" +
                                                                                                                                    "04,Employees1,Employees) \r\n    FROM (\r\n        SELECT \r\n            T.EmployeeID" +
                                                                                                                                    " AS Employees_EmployeeID, \r\n            T.LastName AS Employees_LastName, \r\n    " +
                                                                                                                                    "        T.FirstName AS Employees_FirstName, \r\n            T.Title AS Employees_T" +
                                                                                                                                    "itle, \r\n            T.TitleOfCourtesy AS Employees_TitleOfCourtesy, \r\n          " +
                                                                                                                                    "  T.BirthDate AS Employees_BirthDate, \r\n            T.HireDate AS Employees_Hire" +
                                                                                                                                    "Date, \r\n            T.Address AS Employees_Address, \r\n            T.City AS Empl" +
                                                                                                                                    "oyees_City, \r\n            T.Region AS Employees_Region, \r\n            T.PostalCo" +
                                                                                                                                    "de AS Employees_PostalCode, \r\n            T.Country AS Employees_Country, \r\n    " +
                                                                                                                                    "        T.HomePhone AS Employees_HomePhone, \r\n            T.Extension AS Employe" +
                                                                                                                                    "es_Extension, \r\n            T.Photo AS Employees_Photo, \r\n            T.Notes AS" +
                                                                                                                                    " Employees_Notes, \r\n            T.PhotoPath AS Employees_PhotoPath, \r\n          " +
                                                                                                                                    "  True AS _from0, \r\n            T.ReportsTo AS [SYS_C009204.Employees.EmployeeID" +
                                                                                                                                    "]\r\n        FROM NorthwindEFModelStoreContainer.Employees AS T\r\n    ) AS T1");
                                                                                                                        }
                                                                                                                        else
                                                                                                                        {
                                                                                                                            if ((index == 28))
                                                                                                                            {
                                                                                                                                // vista devuelta para NorthwindEFModelContext.Regions
                                                                                                                                return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.Regions", @"
    SELECT VALUE -- Constructing Regions
        NorthwindEFModel.Regions(T1.Regions_RegionID, T1.Regions_RegionDescription)
    FROM (
        SELECT 
            T.RegionID AS Regions_RegionID, 
            T.RegionDescription AS Regions_RegionDescription, 
            True AS _from0
        FROM NorthwindEFModelStoreContainer.Regions AS T
    ) AS T1");
                                                                                                                            }
                                                                                                                            else
                                                                                                                            {
                                                                                                                                if ((index == 29))
                                                                                                                                {
                                                                                                                                    // vista devuelta para NorthwindEFModelContext.Territories
                                                                                                                                    return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.Territories", @"
    SELECT VALUE -- Constructing Territories
        NorthwindEFModel.Territories(T1.Territories_TerritoryID, T1.Territories_TerritoryDescription) WITH 
        RELATIONSHIP(CREATEREF(NorthwindEFModelContext.Regions, ROW(T1.[SYS_C009226.Regions.RegionID]),NorthwindEFModel.Regions),NorthwindEFModel.SYS_C009226,Territories,Regions) 
    FROM (
        SELECT 
            T.TerritoryID AS Territories_TerritoryID, 
            T.TerritoryDescription AS Territories_TerritoryDescription, 
            True AS _from0, 
            T.RegionID AS [SYS_C009226.Regions.RegionID]
        FROM NorthwindEFModelStoreContainer.Territories AS T
    ) AS T1");
                                                                                                                                }
                                                                                                                                else
                                                                                                                                {
                                                                                                                                    if ((index == 30))
                                                                                                                                    {
                                                                                                                                        // vista devuelta para NorthwindEFModelContext.SYS_C009204
                                                                                                                                        return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.SYS_C009204", @"
    SELECT VALUE -- Constructing SYS_C009204
        NorthwindEFModel.SYS_C009204(T3.[SYS_C009204.Employees], T3.[SYS_C009204.Employees1])
    FROM (
        SELECT -- Constructing Employees
            CreateRef(NorthwindEFModelContext.Employees, row(T2.[SYS_C009204.Employees.EmployeeID]),NorthwindEFModel.Employees) AS [SYS_C009204.Employees], 
            T2.[SYS_C009204.Employees1]
        FROM (
            SELECT -- Constructing Employees1
                CreateRef(NorthwindEFModelContext.Employees, row(T1.[SYS_C009204.Employees1.EmployeeID]),NorthwindEFModel.Employees) AS [SYS_C009204.Employees1], 
                T1.[SYS_C009204.Employees.EmployeeID]
            FROM (
                SELECT 
                    T.ReportsTo AS [SYS_C009204.Employees.EmployeeID], 
                    T.EmployeeID AS [SYS_C009204.Employees1.EmployeeID], 
                    True AS _from0
                FROM NorthwindEFModelStoreContainer.Employees AS T
                WHERE T.ReportsTo IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
                                                                                                                                    }
                                                                                                                                    else
                                                                                                                                    {
                                                                                                                                        if ((index == 31))
                                                                                                                                        {
                                                                                                                                            // vista devuelta para NorthwindEFModelContext.SYS_C009226
                                                                                                                                            return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.SYS_C009226", @"
    SELECT VALUE -- Constructing SYS_C009226
        NorthwindEFModel.SYS_C009226(T3.[SYS_C009226.Regions], T3.[SYS_C009226.Territories])
    FROM (
        SELECT -- Constructing Regions
            CreateRef(NorthwindEFModelContext.Regions, row(T2.[SYS_C009226.Regions.RegionID]),NorthwindEFModel.Regions) AS [SYS_C009226.Regions], 
            T2.[SYS_C009226.Territories]
        FROM (
            SELECT -- Constructing Territories
                CreateRef(NorthwindEFModelContext.Territories, row(T1.[SYS_C009226.Territories.TerritoryID]),NorthwindEFModel.Territories) AS [SYS_C009226.Territories], 
                T1.[SYS_C009226.Regions.RegionID]
            FROM (
                SELECT 
                    T.RegionID AS [SYS_C009226.Regions.RegionID], 
                    T.TerritoryID AS [SYS_C009226.Territories.TerritoryID], 
                    True AS _from0
                FROM NorthwindEFModelStoreContainer.Territories AS T
            ) AS T1
        ) AS T2
    ) AS T3");
                                                                                                                                        }
                                                                                                                                        else
                                                                                                                                        {
                                                                                                                                            if ((index == 32))
                                                                                                                                            {
                                                                                                                                                // vista devuelta para NorthwindEFModelContext.EmployeesTerritories
                                                                                                                                                return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.EmployeesTerritories", @"
    SELECT VALUE -- Constructing EmployeesTerritories
        NorthwindEFModel.EmployeesTerritories(T3.EmployeesTerritories_Employees, T3.EmployeesTerritories_Territories)
    FROM (
        SELECT -- Constructing Employees
            CreateRef(NorthwindEFModelContext.Employees, row(T2.EmployeesTerritories_Employees_EmployeeID),NorthwindEFModel.Employees) AS EmployeesTerritories_Employees, 
            T2.EmployeesTerritories_Territories
        FROM (
            SELECT -- Constructing Territories
                CreateRef(NorthwindEFModelContext.Territories, row(T1.EmployeesTerritories_Territories_TerritoryID),NorthwindEFModel.Territories) AS EmployeesTerritories_Territories, 
                T1.EmployeesTerritories_Employees_EmployeeID
            FROM (
                SELECT 
                    T.EmployeeID AS EmployeesTerritories_Employees_EmployeeID, 
                    T.TerritoryID AS EmployeesTerritories_Territories_TerritoryID, 
                    True AS _from0
                FROM NorthwindEFModelStoreContainer.EmployeesTerritories AS T
            ) AS T1
        ) AS T2
    ) AS T3");
                                                                                                                                            }
                                                                                                                                            else
                                                                                                                                            {
                                                                                                                                                if ((index == 33))
                                                                                                                                                {
                                                                                                                                                    // vista devuelta para NorthwindEFModelStoreContainer.OracleDataTypes
                                                                                                                                                    return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.OracleDataTypes", @"
    SELECT VALUE -- Constructing OracleDataTypes
        [NorthwindEFModel.Store].OracleDataTypes(T1.OracleDataTypes_ID, T1.OracleDataTypes_GuidColumn)
    FROM (
        SELECT 
            T.ID AS OracleDataTypes_ID, 
            T.GuidColumn AS OracleDataTypes_GuidColumn, 
            True AS _from0
        FROM NorthwindEFModelContext.OracleDataTypes AS T
    ) AS T1");
                                                                                                                                                }
                                                                                                                                                else
                                                                                                                                                {
                                                                                                                                                    if ((index == 34))
                                                                                                                                                    {
                                                                                                                                                        // vista devuelta para NorthwindEFModelContext.OracleDataTypes
                                                                                                                                                        return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.OracleDataTypes", @"
    SELECT VALUE -- Constructing OracleDataTypes
        NorthwindEFModel.OracleDataTypes(T1.OracleDataTypes_ID, T1.OracleDataTypes_GuidColumn)
    FROM (
        SELECT 
            T.ID AS OracleDataTypes_ID, 
            T.GuidColumn AS OracleDataTypes_GuidColumn, 
            True AS _from0
        FROM NorthwindEFModelStoreContainer.OracleDataTypes AS T
    ) AS T1");
                                                                                                                                                    }
                                                                                                                                                    else
                                                                                                                                                    {
                                                                                                                                                        if ((index == 35))
                                                                                                                                                        {
                                                                                                                                                            // vista devuelta para NorthwindEFModelStoreContainer.PreviousEmployees
                                                                                                                                                            return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelStoreContainer.PreviousEmployees", "\r\n    SELECT VALUE -- Constructing PreviousEmployees\r\n        [NorthwindEFModel.S" +
                                                                                                                                                                    "tore].PreviousEmployees(T1.PreviousEmployees_EmployeeID, T1.PreviousEmployees_La" +
                                                                                                                                                                    "stName, T1.PreviousEmployees_FirstName, T1.PreviousEmployees_Title, T1.PreviousE" +
                                                                                                                                                                    "mployees_TitleOfCourtesy, T1.PreviousEmployees_BirthDate, T1.PreviousEmployees_H" +
                                                                                                                                                                    "ireDate, T1.PreviousEmployees_Address, T1.PreviousEmployees_City, T1.PreviousEmp" +
                                                                                                                                                                    "loyees_Region, T1.PreviousEmployees_PostalCode, T1.PreviousEmployees_Country, T1" +
                                                                                                                                                                    ".PreviousEmployees_HomePhone, T1.PreviousEmployees_Extension, T1.PreviousEmploye" +
                                                                                                                                                                    "es_Photo, T1.PreviousEmployees_Notes, T1.PreviousEmployees_PhotoPath)\r\n    FROM " +
                                                                                                                                                                    "(\r\n        SELECT \r\n            T.EmployeeID AS PreviousEmployees_EmployeeID, \r\n" +
                                                                                                                                                                    "            T.LastName AS PreviousEmployees_LastName, \r\n            T.FirstName " +
                                                                                                                                                                    "AS PreviousEmployees_FirstName, \r\n            T.Title AS PreviousEmployees_Title" +
                                                                                                                                                                    ", \r\n            T.TitleOfCourtesy AS PreviousEmployees_TitleOfCourtesy, \r\n      " +
                                                                                                                                                                    "      T.BirthDate AS PreviousEmployees_BirthDate, \r\n            T.HireDate AS Pr" +
                                                                                                                                                                    "eviousEmployees_HireDate, \r\n            T.Address AS PreviousEmployees_Address, " +
                                                                                                                                                                    "\r\n            T.City AS PreviousEmployees_City, \r\n            T.Region AS Previo" +
                                                                                                                                                                    "usEmployees_Region, \r\n            T.PostalCode AS PreviousEmployees_PostalCode, " +
                                                                                                                                                                    "\r\n            T.Country AS PreviousEmployees_Country, \r\n            T.HomePhone " +
                                                                                                                                                                    "AS PreviousEmployees_HomePhone, \r\n            T.Extension AS PreviousEmployees_E" +
                                                                                                                                                                    "xtension, \r\n            T.Photo AS PreviousEmployees_Photo, \r\n            T.Note" +
                                                                                                                                                                    "s AS PreviousEmployees_Notes, \r\n            T.PhotoPath AS PreviousEmployees_Pho" +
                                                                                                                                                                    "toPath, \r\n            True AS _from0\r\n        FROM NorthwindEFModelContext.Previ" +
                                                                                                                                                                    "ousEmployees AS T\r\n    ) AS T1");
                                                                                                                                                        }
                                                                                                                                                        else
                                                                                                                                                        {
                                                                                                                                                            if ((index == 36))
                                                                                                                                                            {
                                                                                                                                                                // vista devuelta para NorthwindEFModelContext.PreviousEmployees
                                                                                                                                                                return new System.Collections.Generic.KeyValuePair<string, string>("NorthwindEFModelContext.PreviousEmployees", "\r\n    SELECT VALUE -- Constructing PreviousEmployees\r\n        NorthwindEFModel.Pr" +
                                                                                                                                                                        "eviousEmployees(T1.PreviousEmployees_EmployeeID, T1.PreviousEmployees_LastName, " +
                                                                                                                                                                        "T1.PreviousEmployees_FirstName, T1.PreviousEmployees_Title, T1.PreviousEmployees" +
                                                                                                                                                                        "_TitleOfCourtesy, T1.PreviousEmployees_BirthDate, T1.PreviousEmployees_HireDate," +
                                                                                                                                                                        " T1.PreviousEmployees_Address, T1.PreviousEmployees_City, T1.PreviousEmployees_R" +
                                                                                                                                                                        "egion, T1.PreviousEmployees_PostalCode, T1.PreviousEmployees_Country, T1.Previou" +
                                                                                                                                                                        "sEmployees_HomePhone, T1.PreviousEmployees_Extension, T1.PreviousEmployees_Photo" +
                                                                                                                                                                        ", T1.PreviousEmployees_Notes, T1.PreviousEmployees_PhotoPath)\r\n    FROM (\r\n     " +
                                                                                                                                                                        "   SELECT \r\n            T.EmployeeID AS PreviousEmployees_EmployeeID, \r\n        " +
                                                                                                                                                                        "    T.LastName AS PreviousEmployees_LastName, \r\n            T.FirstName AS Previ" +
                                                                                                                                                                        "ousEmployees_FirstName, \r\n            T.Title AS PreviousEmployees_Title, \r\n    " +
                                                                                                                                                                        "        T.TitleOfCourtesy AS PreviousEmployees_TitleOfCourtesy, \r\n            T." +
                                                                                                                                                                        "BirthDate AS PreviousEmployees_BirthDate, \r\n            T.HireDate AS PreviousEm" +
                                                                                                                                                                        "ployees_HireDate, \r\n            T.Address AS PreviousEmployees_Address, \r\n      " +
                                                                                                                                                                        "      T.City AS PreviousEmployees_City, \r\n            T.Region AS PreviousEmploy" +
                                                                                                                                                                        "ees_Region, \r\n            T.PostalCode AS PreviousEmployees_PostalCode, \r\n      " +
                                                                                                                                                                        "      T.Country AS PreviousEmployees_Country, \r\n            T.HomePhone AS Previ" +
                                                                                                                                                                        "ousEmployees_HomePhone, \r\n            T.Extension AS PreviousEmployees_Extension" +
                                                                                                                                                                        ", \r\n            T.Photo AS PreviousEmployees_Photo, \r\n            T.Notes AS Pre" +
                                                                                                                                                                        "viousEmployees_Notes, \r\n            T.PhotoPath AS PreviousEmployees_PhotoPath, " +
                                                                                                                                                                        "\r\n            True AS _from0\r\n        FROM NorthwindEFModelStoreContainer.Previo" +
                                                                                                                                                                        "usEmployees AS T\r\n    ) AS T1");
                                                                                                                                                            }
                                                                                                                                                        }
                                                                                                                                                    }
                                                                                                                                                }
                                                                                                                                            }
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            throw new System.IndexOutOfRangeException();
        }
    }
}
